### ISSUE TITLE
ModuleNotFoundError: No module named 'ordered_set'

### ISSUE THREAD

**Issue by LEv145** [Erotemic/mkinit#28]
**Describe the bug**
ModuleNotFoundError: No module named 'ordered_set'

**To Reproduce**
Install module 
(I use poetry: poetry add mkinit)

```python
mkinit -w --black --recursive --relative --nomods src/bot_abuse/api
```

**Desktop (please complete the following information):**
 - Ubelt 1.1.2
 - Python version 3.10
 - Mkinit 0.3.4

**Additional context**
```
Traceback (most recent call last):
  File "/home/lev/.cache/pypoetry/virtualenvs/bot_abuse--vxiy89I-py3.10/bin/mkinit", line 5, in <module>
    from mkinit.__main__ import main
  File "/home/lev/.cache/pypoetry/virtualenvs/bot_abuse--vxiy89I-py3.10/lib/python3.10/site-packages/mkinit/__init__.py", line 14, in <module>
    from mkinit import static_mkinit
  File "/home/lev/.cache/pypoetry/virtualenvs/bot_abuse--vxiy89I-py3.10/lib/python3.10/site-packages/mkinit/static_mkinit.py", line 12, in <module>
    from mkinit.top_level_ast import TopLevelVisitor
  File "/home/lev/.cache/pypoetry/virtualenvs/bot_abuse--vxiy89I-py3.10/lib/python3.10/site-packages/mkinit/top_level_ast.py", line 5, in <module>
    from ordered_set import OrderedSet as oset
ModuleNotFoundError: No module named 'ordered_set'
```

**Comment by Erotemic** [comment]
This seems to be fixed in the latest branch. I had vendored in ordered_set to reduce dependencies, but I guess I forgot to update it when I released the last version. I'll release 1.0.0 soon, which will fix this. In the meantime you should be able to `pip install ordered_set` which will patch the problem.
