### ISSUE TITLE
vist_Try exception trying to extend() an OrderedSet

### ISSUE THREAD

**Issue by mzpqnxow** [Erotemic/mkinit#5]
While I'm not able to track down why my codebase triggered this, I encountered this, which appears to be a simple bug in mkinit. I assume it is a rare code path and hadn't been well tested for whatever reason. I redacted part of the path. I have a patch for this I will submit separately as a PR

```
$ mkinit mymodule/
ns = {'modname_or_path': 'mymodule/', 'dry': False, 'nomods': False, 'noattrs': False, 'relative': False, 'noall': False, 'ignore_all': False}
OrderedSet()
OrderedSet(['adapt_date', 'adapt_range'])
Traceback (most recent call last):
  File "/data/venv/bin/mkinit", line 11, in <module>
    sys.exit(main())
  File "/data/venv/local/lib/python2.7/site-packages/mkinit/__main__.py", line 60, in main
    options=options, dry=ns['dry'])
  File "/data/venv/local/lib/python2.7/site-packages/mkinit/static_mkinit.py", line 57, in autogen_init
    use_all=use_all, options=options)
  File "/data/venv/local/lib/python2.7/site-packages/mkinit/static_mkinit.py", line 92, in static_init
    use_all=use_all)
  File "/data/venv/local/lib/python2.7/site-packages/mkinit/static_mkinit.py", line 210, in _static_parse_imports
    top_level = TopLevelVisitor.parse(source)
  File "/data/venv/local/lib/python2.7/site-packages/mkinit/top_level_ast.py", line 108, in parse
    self.visit(pt)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/data/venv/local/lib/python2.7/site-packages/mkinit/top_level_ast.py", line 207, in visit_Try
    body_attrs.extend(orelse_attrs)
AttributeError: 'OrderedSet' object has no attribute 'extend'
(venv) $
```

**Comment by mzpqnxow** [comment]
aaaannndddddd your master has already corrected this.. so nevermind :>

**Comment by Erotemic** [comment]
Is the version on pypi broken? If so I'll need to update.

**Comment by mzpqnxow** [comment]
Yes, that the latest available.

**Comment by Erotemic** [comment]
I just tagged the current master as `0.1.0` and uploaded to pypi. Thanks for the report!

**Comment by mzpqnxow** [comment]
No problem. I have a rather large codebase that I’ll be running it against, if I find any other issues I’ll let you know and provide a PR if it isn’t terribly involved.

Thanks for the quick fix!
